### ISSUE TITLE
Update startup script to use network option

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-scripts#102]
With the issue https://github.com/LiskHQ/lisk/issues/398 when PR https://github.com/LiskHQ/lisk/pull/2149 will be ready. We have to update all startup scripts and configuration to follow network command line option to start the node for specific network. 

https://github.com/LiskHQ/lisk-scripts/blob/21f2e4af14f0ab9f00eec3a90f8c44d864dd373b/packaged/etc/pm2-lisk.json#L14

https://github.com/LiskHQ/lisk-scripts/blob/21f2e4af14f0ab9f00eec3a90f8c44d864dd373b/packaged/etc/pm2-snapshot.json#L15

So above code will be come.

```
"args": "-c config.json -n devnet",
```

Available networks that can be configured are `devnet`, `betanet`, `testnet` and `mainnet`.

**Comment by fchavant** [comment]
Is this something lisk-build should be doing maybe?
lisk-build pulls files lisk-scripts and puts them into place and gets called with a `-n` switch so it'd be trivial to modify `etc/pm2-*.json` there.

**Comment by fchavant** [comment]
My point is this is something that should be done in `lisk-build` and there is an issue over there. This issue here in lisk-scripts could be closed IMO.

**Comment by nazarhussain** [comment]
Yes please discuss with @Nazgolze and refer the issue in lisk-build and close this issue.

**Comment by Nazgolze** [comment]
Closing in favor of doing this in lisk-build
