### ISSUE TITLE
Verify the usage of version and minVersion from old config.json

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-scripts#106]
With recent changes in core 1.1.x, we had moved `version` and `minVersion` from the `config.json` to `package.json`

Need to validate any usage of these attributes in this project.

**Comment by fchavant** [comment]
I cannot find any usage of `version` or `minVersion` on the 0.3.0 branch.

**Comment by Nazgolze** [comment]
Closing this since version / minVersion isn't used here
