### ISSUE TITLE
Update min-uptime for pm2 to compensate chain validation time

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-scripts#119]
## Expected Behavior 
If application exit with status code 1, the pm2 should restart it upto the maximum retries defined. 

## Current Behavior 
Since application is doing chain validation on startup and it take longer time now (more than 3 sec) currently defined `min-uptime` in pm2. So if application exits during chain validation after 3 sec, pm2 restart the application but didn't count it as retries. 

https://github.com/LiskHQ/lisk-scripts/blob/db15327bc0b01ca656ad09ef63e4f80ca804725b/packaged/etc/pm2-lisk.json#L15-L16

**Comment by nazarhussain** [comment]
Introduced by changes in https://github.com/LiskHQ/lisk/issues/2249

**Comment by Nazgolze** [comment]
Closed by #120 and #121
