### ISSUE TITLE
Don't run update_config.js while upgrading to the same as installed version

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-scripts#129]
### Expected behavior

While running `installLisk.sh upgrade` from version `X` to version `X`, the update_config.js should not be run. The config.json should not be migrated.

### Actual behavior
During `installLisk.sh upgrade`  from version `X` to version `X`, `update_config.js` is being run:
https://github.com/LiskHQ/lisk-scripts/blob/development/downloaded/installLisk.sh#L261

The script is not designed to be run trying to update config.json do the same version. More details explained in https://github.com/LiskHQ/lisk/issues/2317.

### Steps to reproduce

`bash installLisk.sh upgrade` doesn't modify `config.json` while running for the same version.

**Comment by Nazgolze** [comment]
Closed by #130
