### ISSUE TITLE
Wrong path checks

### ISSUE THREAD

**Issue by vekexasia** [LiskHQ/lisk-scripts#131]
Hello, 

I've been helping out @corsaro1 with an issue about lisk_bridge.sh. I'm pretty sure in the lines below you meant to use `cd "$var" && pwd -P` or `cd -P "$var" && pwd` cause the if below does not mean anything to me considering `cd -P "$var"` does not output anything in the shell.

https://github.com/LiskHQ/lisk-scripts/blob/dce31ace4e705ca3254b2690528f50646b0c64df/downloaded/lisk_bridge.sh#L65-L68

**Comment by Nazgolze** [comment]
Ah whoops, you're right

**Comment by Nazgolze** [comment]
Closed by #132
