### ISSUE TITLE
installLisk.sh does not check if jq is installed on the system

### ISSUE THREAD

**Issue by gregorst3** [LiskHQ/lisk-scripts#141]
Hello, Gregorst here
There is a minor bug in **installLisk.sh**. Bug that is present since jq is used.
The script does not check if jq is installed and, if not, **_it is not able to restore the config.json_** in the new installation **losing all of the precedent configuration**.

**Comment by Nazgolze** [comment]
@gregorst3 @karek314 - try it again when you get the chance, the version on downloads.lisk.io should be up to date now. It should be using the jq that comes bundled with the lisk-core that is being installed

**Comment by karek314** [comment]
Thanks! But actually, that check I proposed here https://github.com/LiskHQ/lisk-scripts/pull/140 shouldn't be much of an problem to add, eventually - it's better if it fails at check rather then leaving user with purged config.

**Comment by Nazgolze** [comment]
Closing since installLisk.sh uses the jq that comes bundled with the new version of lisk core that it downloads.
Will note that #160 made a bunch of improvements to installLisk.sh, which will be on https://downloads.lisk.io/lisk/test once we release 1.1.0 to testnet
