### ISSUE TITLE
Update lisk_snapshot.sh for core 1.1.

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-scripts#148]
Relates to https://github.com/LiskHQ/lisk-build/issues/310

- [`LISK_CONFIG`](https://github.com/LiskHQ/lisk-scripts/blob/0.3.2/packaged/lisk_snapshot.sh#L38) needs to be changed (see [LiskHQ/lisk-scripts#116](https://github.com/LiskHQ/lisk-scripts/pull/116/))
- `-s` needs to be changed (replaced?) for the same reason

**Comment by Nazgolze** [comment]
Closed by #149
