### ISSUE TITLE
Source env.sh before shared.sh in installLisk.sh

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-scripts#150]
Since https://github.com/LiskHQ/lisk-scripts/pull/149 `env.sh` must be sourced before `shared.sh`.
This must be done in https://github.com/LiskHQ/lisk-scripts/blob/v0.3.2/downloaded/installLisk.sh#L243

Note that while the current ordering causes an error message to be shown the functionality of `installLisk.sh` is not affected.

**Comment by Nazgolze** [comment]
Closed by #153
