### ISSUE TITLE
Update the snapshot round value to a negative integer

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-scripts#190]
As per the specifications in https://github.com/LiskHQ/lisk/issues/2843 we should updated configuration to have a negative range specified for full rounds. 

https://github.com/LiskHQ/lisk-scripts/blob/db4a84d5701ef00be719a0c276eab2e647f27962/packaged/etc/pm2-snapshot.json#L15

**Comment by fchavant** [comment]
The relevant PM2 configuration file now lives in the LiskHQ/lisk repository (see https://github.com/LiskHQ/lisk/pull/3044)
