### ISSUE TITLE
Update Lisk scripts to handle folder restructure changes in Lisk core

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-scripts#195]
## Actual:
Failed to upgrade node from `1.5.0` to `1.6.0`
```
Copying config.json entries from previous installation
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/home/lisk/lisk-test/scripts/update_config.js'
```

## Expected:
Should be able able upgrade to new releases

**Comment by fchavant** [comment]
@ManuGowda does `update_config.js` live in 1.6?

**Comment by fchavant** [comment]
Waiting for https://github.com/LiskHQ/lisk/issues/3255.

**Comment by fchavant** [comment]
Will not be needed after https://github.com/LiskHQ/lisk/pull/3259
