### ISSUE TITLE
Upgrade lisk bridge script to not bundled instead work independently

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-scripts#37]
## Current Behavior 

Currently, we bundled `lisk_bridge.sh` inside our build process and it is shipped along with the build. 

## Problem 

The `lisk_bridge.sh` script is actually overriding the Lisk Home directory with the new release. So it seems not feasible to execute that script from a directory which is going to be overwritten. 

## Suggested Solution 

Update  `lisk_bridge.sh` to not bundled in the release and can be executed independently. So whenever we a user need to migrate can run a single command to download and execute this script and point it to lisk home directory. 

```
\curl -sSL https://downloads.lisk.io/lisk/lisk_bridge.sh | bash -s /home/lisk/lisk-test
```

**Comment by Nazgolze** [comment]
Due to #41, this is already complete. Closing issue
