### ISSUE TITLE
Add support for non-interactive mode in installLisk.sh

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-scripts#53]
We have a need for it in one of our Jenkins jobs.

This will, if there's no TTY:

- disable prereq checks
- force release to be specified as an argument (the other ones can use the defaults), and if it isn't, the script will bail out

**Comment by nazarhussain** [comment]
@Nazgolze This is not just for the jenkins job. We can't always install builds manually, if I have many servers. There must be an automated tool doing this for us. So I believe whenever any tool involved we need a non-interactive mode for it.

**Comment by Nazgolze** [comment]
Closed by #57
