### ISSUE TITLE
Remove sudo from installLisk.sh

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-scripts#54]
There are too many good reasons to do this. This will also remove the ntp check and the logrotate config addition will no longer happen
As a result, the following other issues will get closed when this is completed:

- https://github.com/LiskHQ/lisk-scripts/issues/2
- https://github.com/LiskHQ/lisk-scripts/issues/4
- https://github.com/LiskHQ/lisk-scripts/issues/16

https://github.com/LiskHQ/lisk-scripts/issues/53 also stands to benefit from this

**Comment by fchavant** [comment]
Documentation must be updated to reflect that setting up NTP is a prerequisite and should mention log rotation as an optional post-installation step.
