### ISSUE TITLE
installLisk.sh with -u to a another url, lisk is still downloaded from the old URL

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-scripts#6]
From: https://github.com/LiskHQ/lisk-build/issues/228

**Comment by Nazgolze** [comment]
-u is not for downloading lisk, but for downloading the snapshot.
I tested this and it works as expected (bash installLisk.sh upgrade -h -u https://testnet-snapshot.lisknode.io downloads and uses snapshot from gr33ndrag0n)
