### ISSUE TITLE
Ensure created snapshots work

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-scripts#80]
### Description
We are frequently facing the situation of providing broken snapshots. Automation of the process with a Jenkins job would indicate it, so we are aware of the problem and can start fixing it as soon as possible.

### Expected behavior
After the snapshot is finished, the validation part starts:
The script cold starts a new Lisk Core instance from the newly created snapshot. After that, repeatedly verifies the Node's height. If the height doesn't grow within the specified time window (let's say 120 sec) it means that the node cannot sync with the network from the provided snapshot. The error should be thrown. Jenkins job responsible for creating snapshots fails.

### Actual behavior
After a snapshot is created, the snapshot validation step is missing. Before dropping the existing DB structures we should ensure, that provided snapshot is fully functioning. 

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by Nazgolze** [comment]
Closed by #82
