### ISSUE TITLE
Rely on Lisk Core process termination while creating snapshot

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk-scripts#81]
When https://github.com/LiskHQ/lisk/issues/2075 is ready, Lisk Core running in the snapshot mode will terminate when snapshot finished. No need to "grep" for that: https://github.com/LiskHQ/lisk-scripts/blob/development/packaged/lisk_snapshot.sh#L177.

**Comment by Nazgolze** [comment]
Closed by #82
