### ISSUE TITLE
Update lisk_bridge script to stop the node if missed the height

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-scripts#85]
We need to do following changes to lisk_bridge.sh script 

1. If missed the particular height that was passed, we need to stop the instance and show user a message that he need to upgrade manually now. 
2. Provide some `echo` output during the lisk_bridge.sh script. Right now when it run it start showing height in console without any other output that can confuse the user. 
3. Fix the error shown during recent test runs
```
/home/nazar/lisk-install-test/lisk-main/env.sh: line 20: cd: ./lisk-main: No such file or directory
```
It was triggered when passed this command
```
bash lisk_bridge.sh -h 210 -n main -f lisk-0.9.8-Linux-x86_64.tar.gz -s ./lisk-main/
```

**Comment by Nazgolze** [comment]
-s doesn't work with relative paths

**Comment by Nazgolze** [comment]
-s "$PWD/lisk-main" does work

**Comment by Nazgolze** [comment]
#87
