### ISSUE TITLE
Issues with lisk_bridge.sh

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-scripts#89]
- usage of `f` flag is not documented
- `installLisk.sh` will not be overwritten if it exists (wget create `installLisk.sh.1` by default) and thus the old script will be used

**Comment by fchavant** [comment]
`--no-clobber` without `--timestamp` will not overwritte an existing file; event with `--timestamp` the local file might not be overwritten.
So we probably should always remove it before downloading it again.

**Comment by Nazgolze** [comment]
Closed by #93
