### ISSUE TITLE
Add feature to clean database after upgrade

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-scripts#92]
While running some tests for migration from 0.9.x to 1.0.x noticed that there is a requirement to clean the database after the upgrade. 

For now identified following: 

- We need to clear the `peers` table after upgrade to avoid conflict between 0.9.x `port` and 1.0.x `wsPort`. 

But there can be future requirements that we can extend this behavior. To acheive a flexible solution we need; 

1. An option `--clean--after-upgrade` in `installLisk.sh` if set will trigger the clean operation
2. For now it will only clean the `peers` table in database 
3. Update `lisk_bridge.sh` to pass this option while calling the `installLisk.sh`

**Comment by fchavant** [comment]
Point 3 is not done yet.
> Update lisk_bridge.sh to pass this option while calling the installLisk.sh

**Comment by Nazgolze** [comment]
Closed by #96
